### ISSUE TITLE
How to check access for reading post into loop for "nobody"

### ISSUE THREAD

**Issue by Trebly** [GM-Alex/user-access-manager#235] opened 2018-04-25 01:37 UTC
Hello Alex,

__URGENT__

After the update to the new version of UAM (from my old version 1.2.14 patched), I was thinking that everything was OK.
But in fact, the loop done (standard) by the list generator W4PL seems <strong>not to skip</strong> a post __which does not belong to the group defined with the read rights for "nobody (visitor)"__. The group is named as waited "visitors" (a post for which this group is not checked should not be visible at all by a visitor, if right have not been defined for "nobody"). The display for content is locked but not excerpt and summary.

In another way to explain : to not view a post excerpt into a list I had simply to not attach the post to the UAMgroup defined as allowed to be read by my "dummy_user_visitor". The current version seems not to work in the same exact way.

Practically in my patch I was substituting for UAM check a "no_user" ($user = null : case of a visitor) by an __UAM_visitor__ (role defined for WP with users roles manager). Then if a post was not associated to a group with the read allowed for the role, UAM was allowing the access to the defined capabilites of the UAM_visitor.

I am not sure that currently UAM functions as I just upon defined for the feature (post attached to group of the "nobody" role. Can you confirm ?

Currently, I have not found any way to do it. In my list of summaries or excerpts I get  All the post published. WP-UAM seems to send their 'excerpt or summary' regardless the UAM group (they are not simply fully readable 'cannot display content'). Then the user can ask "see all" and when the article is displayed the visitor gets the message "you have nor he right..."; It is exactly why I was wanting to avoid.

May be I have missed something. 

So I feel that I am unable to fully hide a post from a loop (for lists) if the post is published while this was one of the features of my "dummy_user_visitor". There were never right of reading anything of a post by default (other special custom right could be defined).

__Is-it true and planned to function as I see ?__

Can you add explanations of the use of "person" into your wiki <a href="https://github.com/GM-Alex/user-access-manager/wiki" rel="noopener" target="_blank"></a>

Best regards

Trebly

**Comment by GM-Alex** [comment] 2018-04-27 06:34
Duplicate of #238

**Closed by GM-Alex** 2018-04-27 06:34 UTC
