### ISSUE TITLE
bbpress post settings are not saved

### ISSUE THREAD

**Issue by smith89er** [GM-Alex/user-access-manager#33] opened 2017-04-24 07:18 UTC
In the latest version 2.01 access settings for posts created in the bbpress forum section aren't saved. The box in the edit-post dialogue is visible, you can check access levels. Anyway, after saving the changes, again no access level is set.
Access levels work fine for regular posts.
Probably relevant plugins for this bug: Buddypress, bbpress
Wordpress version 4.7.4

**Comment by GM-Alex** [comment] 2017-04-24 07:36
I'm currently not able to reproduce the issue. Setting the access groups works for me. So the reason must not bbpress or Buddypress itself. Could you deactivate all other modules expect bbpress and User Access Manager and test again?

**Comment by smith89er** [comment] 2017-04-24 08:04
Hi,

I deactivated all plugins but UAM, Buddypress, bbpress in sandbox. The 
issue was still there. I tested further and was able to resolve it by 
reseting the UAM settings. Obviously this is something I don't want to 
do on my productive site, as I would have to set up all accesses again. 
Currently I rolled back to the previous version.

I'd assume the problem is in the updating process. Perhaps try to 
reproduce by setting up a previous version of UAM (I run 1.2.14) beside 
bbpress / Buddypress. Assign usergroup to a board, then update to UAM 2 
and check the settings.

Thanks for your support!


Am 24.04.2017 um 09:36 schrieb Alexander Schneider:

**Comment by GM-Alex** [comment] 2017-04-24 08:09
Yes seems like that see https://wordpress.org/support/topic/bugs-in-portfolio-settings-and-group-name-after-update-to-2-01-database-update/

**Comment by GM-Alex** [comment] 2017-04-24 08:14
Ok I found the reason, maybe you give it a try. Go to your database and run `UPDATE wp_uam_accessgroup_to_object SET general_object_type = '_post_' WHERE general_object_type = ''`

**Comment by smith89er** [comment] 2017-04-24 08:19
yes, this fixed it for me. Thank you!


Am 24.04.2017 um 10:14 schrieb Alexander Schneider:

**Comment by GM-Alex** [comment] 2017-04-24 11:10
Fixed with 2.0.2

**Closed by GM-Alex** 2017-04-24 11:10 UTC
Labels: bug
