### ISSUE TITLE
User details not displaying the backend

### ISSUE THREAD

**Issue by dashraven** [GM-Alex/user-access-manager#193] opened 2017-12-05 11:53 UTC
For some reason, I cannot see my user's details on the backend, even thought all of the content is in the database and I can export it with another plugin.

Any possibility for this? Other plugin that might be causing this?

I have Version 2.1.5

**Comment by GM-Alex** [comment] 2017-12-06 07:51
I'm not able to reproduce this. Please use the latest version 2.1.9. If the issue still exists, disable all other plugins and see if it's still there. If yes, please come back an wirte down when it exactly comes to this issue (which role has the user and so on). Until that I will close the issue here.

**Closed by GM-Alex** 2017-12-06 07:51 UTC
