### ISSUE TITLE
A way to check into a post loop if a 'defined action' is allowed by  UAM ?

### ISSUE THREAD

**Issue by Trebly** [GM-Alex/user-access-manager#237] opened 2018-04-26 15:04 UTC
Hello Alex,

I simplify my previous subject (How to check access for reading post into loop for "nobody"): 

**What is (or it is) a way to check with php if UAM allows "access" to a defined post->ID (which capabilities ?) ?**

Currently 'access' seems to be checked by UAM for content with capabilities "read" "write", then when a user tries to view the post content or edit (if button is accessible) UAM can refuse and sends the error message (or generates others options when access is denied). 

**How can a developer can check the access rights given by UAM.**

This question can be extended to other "capabilties" inherited for the current "object". This can be for example "read-post-excerpt", then a check into the excerpt.php will allow to list only "objects instances" for which UAM access is allowed.

How to do this ?
Thanks for answering.

Best regards

Trebly
________________________________________________________________________________
**Note about development** : since my last question I have enhanced UAM which now attaches to user->ID=0 (visitor) the 'person' role capabilities and for my test for those of the role 'uam-visitor', Then now user->0 has the roles 'person' and 'uam-visitor' when UAM is activated.
But for now I have not found where is the function which can check the uam access for a defined object. To much time to bone all the code without any doc.

**Comment by GM-Alex** [comment] 2018-04-27 06:33
Duplicate of #238

**Closed by GM-Alex** 2018-04-27 06:33 UTC
