### ISSUE TITLE
pages are hidden in hierarchy, starting from version 1.2.6.9

### ISSUE THREAD

**Issue by nwoetzel** [GM-Alex/user-access-manager#8] opened 2017-01-12 15:47 UTC
After upgrading 1.2.6.8->1.2.6.9 (for all versions up to 1.2.14) child pages in hierarchies are denied:
So I have
* page A: group A
* page B (with A as parent): group B
* group A and B each have 'read all' and 'write group'
* lockRecursive is disabled

when a user of group B is logged in, page B cannot be seen, and the permission to edit is denied
I **expect** that **user of group B** can always see and **edit page with Access to group B**.
* If I remove the parent of page B, all is fine and user of group B can see it in the page list and edit.
* If I add page group B to page A, all is fine and user of group B can see it in the page list and edit.

https://github.com/GM-Alex/user-access-manager/compare/1.2.8...1.2.9
Since there are quite some changes in the design between the two versions, I might need a hint to track it down.
Thanks.

**Comment by GM-Alex** [comment] 2017-01-12 18:17
I think the problem is here https://github.com/GM-Alex/user-access-manager/blob/master/class/UamAccessHandler.php#L687 You could try to remove the map and see if it works again, but I think the issue came from somewhere here.

**Comment by GM-Alex** [comment] 2017-01-12 18:20
You can see track the progress for the next big release here: https://github.com/GM-Alex/user-access-manager/tree/next

**Comment by nwoetzel** [comment] 2017-01-12 18:26
Removing that part let the user of group B see any page.
But I think this is the right place to dig into.
I think I understand the intent of checking against the tree when the type of the post is hierarchical. But $oConfig->lockRecursive() should influence that portion of the code also, or should it not?

**Comment by GM-Alex** [comment] 2017-01-12 18:28
Yes I think I just forget that and tested only against the recursive behavior, one reason more for the refactoring and unit tests...

**Comment by GM-Alex** [comment] 2017-04-13 21:58
Fixed with 2.0.0

**Closed by GM-Alex** 2017-04-13 21:58 UTC
Labels: bug
